### ISSUE TITLE
Unable to customize the gutter styles

### ISSUE THREAD

**Issue by calthomson** [praneshr/react-diff-viewer#10]
Hi!

First off, I love the component! It's great that you've built the styling customizability in so cleanly, too. However, I am running into an issue.

I'm looking for a way to target the leftmost gutter for `splitView={false}`:

![image](https://user-images.githubusercontent.com/8645285/57103860-b877b000-6cdb-11e9-8afc-214ad0c4f618.png)

I want to hide this gutter, and be able to change the width of the gutters etc..

Even this does nothing:

```
<ReactDiffViewer
  oldValue={someValue}
  newValue={someOtherValue}
  splitView={false}
  styles={
    gutter: {
     visibility: 'hidden',
    }
  }
/>
```

**Comment by praneshr** [comment]
Fixed in [v1.1.0](https://github.com/praneshr/react-diff-viewer/releases/tag/v1.1.0)

Now, you can use `rightGutter` or `leftGutter` to style gutters. In your case, you can do the following.
```
<ReactDiffViewer
  oldValue={someValue}
  newValue={someOtherValue}
  splitView={false}
  styles={
    leftGutter: {
     display: 'none',
    }
  }
/>
```

**Comment by calthomson** [comment]
@praneshr This is great! Thank you!

**Comment by ebramanti** [comment]
For those trying to replicate the above on `v3.1.1`, `leftGutter` and `rightGutter` styles were removed. I was able to target the left gutter using the following styles object:
```ts
{
  gutter: {
    ":first-of-type": {
      display: "none",
    }
  }
}
```
