### ISSUE TITLE
When oldValue and newValue is too long , diff viewer container will overflow page

### ISSUE THREAD

**Issue by cczz598** [praneshr/react-diff-viewer#11]
I use this component to compare two similar json string, I set splitView=true. 
But I when some fields is too long in json string, the diff viewer container will overflow page.
![image](https://user-images.githubusercontent.com/5918421/57300909-5b7c5f80-710a-11e9-8058-18d51ec5db88.png)
![image](https://user-images.githubusercontent.com/5918421/57301353-64b9fc00-710b-11e9-9ce1-a4c0ed3ee657.png)

I try to set new styles, but not fix this problem. 
I want both of oldValue and newValue display half of container,  please help me to fix this problem , thx!

**Comment by praneshr** [comment]
This is intentional. If you need word wrapping, add it to the `line` style.

```
<ReactDiffViewer
  oldValue={someValue}
  newValue={someOtherValue}
  styles={
    line: {
    whiteSpace: 'normal',
    }
  }
  splitView
/>```

**Comment by tonyquang** [comment]
who want to resolve this issue if the above solution doesn't work for you
try this
```
styles={{
   line: {
      wordBreak: 'break-all',
   }
}}
```

**Comment by venky216** [comment]
> who want to resolve this issue if the above solution doesn't work for you try this
> 
> ```
> styles={{
>    line: {
>       wordBreak: 'break-all',
>    }
> }}
> ```

Thank you this helped me.
