### ISSUE TITLE
 Empty lines, Removed last lines

### ISSUE THREAD

**Issue by roychoi73** [praneshr/react-diff-viewer#12]
I hope you fix two issues.
1.  On splitView mode, removed last lines of oldValue are located in the newValue area.
2. Empty lines are removed. I want to show empty lines as well.

Actually I have fixed above two issues on my labtop.
And my source is working well.

I hope you check my changes below forked repository.
https://github.com/roychoi73/react-diff-viewer.git

**Comment by praneshr** [comment]
Can you add screenshots for both the cases? It will be more helpful to understand.

**Comment by roychoi73** [comment]
![removed-lines](https://user-images.githubusercontent.com/30612051/57680599-f32d0100-7668-11e9-987a-bf2d8f79b075.png)
![empty-lines](https://user-images.githubusercontent.com/30612051/57680606-f58f5b00-7668-11e9-8bdf-15042169aa27.png)

Please check images.

**Comment by praneshr** [comment]
`react-diff-viewer@v2.0.0-alpha` is now available. The above issue is addressed. It also includes a few other changes. Make sure to check it out and provide feedback. This is not production ready yet. A stable version will be released soon. 

Check [here](https://github.com/praneshr/react-diff-viewer/tree/v2.0) for instructions and documentation.

It will look something like this
![image](https://user-images.githubusercontent.com/10805204/60896794-932b9300-a284-11e9-9803-871090c101c8.png)

**Comment by praneshr** [comment]
Fixed in https://github.com/praneshr/react-diff-viewer/releases/tag/v2.0.0
