### ISSUE TITLE
Only show diffs, not entire file.

### ISSUE THREAD

**Issue by rajuashok** [praneshr/react-diff-viewer#14]
Is there a way to only show the the diff lines and collapse (similar to github) other lines of the file?

**Comment by lambdaxs** [comment]
I also need this feature

**Comment by lambdaxs** [comment]
> Is there a way to only show the the diff lines and collapse (similar to github) other lines of the file?

you can try this npm lib react-gh-like-diff

**Comment by rajuashok** [comment]
Thanks man I actually already switched to that lib. react-gh-like-diff is
GREAT!




Ashok Raju
about.me/ashokraju


ᐧ

**Comment by praneshr** [comment]
I will be added in the next major version

**Comment by jhodges10** [comment]
> It will be added in the next major version

Is there an ETA on the new version?

I would love to integrate this package but that's an important feature for me so that I don't fill up the page.

**Comment by praneshr** [comment]
@jhodges10 The new version will be out by the end of this month.

**Comment by jhodges10** [comment]
> @jhodges10 The new version will be out by the end of this month.

Awesome! We'll plan around that.

**Comment by praneshr** [comment]
`react-diff-viewer@v2.0.0-alpha` is now available. The above issue is addressed. It also includes a few other changes. Make sure to check it out and provide feedback. This is not production ready yet. A stable version will be released soon. 

Check here for instructions and documentation
https://github.com/praneshr/react-diff-viewer/tree/v2.0

**Comment by jhodges10** [comment]
Looks good @praneshr! 

I'll give it a try soon.

**Comment by praneshr** [comment]
Fixed in https://github.com/praneshr/react-diff-viewer/releases/tag/v2.0.0
