### ISSUE TITLE
Question! about file compare

### ISSUE THREAD

**Issue by GeorgiosP** [praneshr/react-diff-viewer#16]
I'm working on a project that needs a diff but not really for code but more documents how is the support for something like that? 
the data I'm consuming will be structured in nodes like this and not just raw text
```
  {
    "id": "00000000-0000-0000-0000-000000000000",
    "priorId": "00000000-0000-0000-0000-000000000001",
    "headingLevel": 1,
    "content": "Short Title",
    "previousContent": null,
    "changeStatus": 1
  }
```

Thanks! 😄

**Comment by praneshr** [comment]
Unfortunately, react-diff-viewer can only handle raw text for now. You can process the file and pass them as a string. `JSON.stringify` should take care of most of the processing.

Closing this. Feel free to reopen if you need more info.
