### ISSUE TITLE
Compile error using strictNullChecks: true on branch v2.0

### ISSUE THREAD

**Issue by mkoyamaRS** [praneshr/react-diff-viewer#17]
Tried to use the alpha version in a project with the following tsconfig compile option
"strictNullChecks": true gives the following error

/node_modules/react-diff-viewer/lib/styles.d.ts
(3,5): Property 'diffContainer' of type 'string | undefined' is not assignable to string index type 'string'.

I did have a solution by changing the index signature of ReactDiffViewerStyles to [key: string]: string | undefined; - after changing this it compiles fine with the option.

**Comment by praneshr** [comment]
Ahh! Thanks for the pointing out the issue. I’ll fix it in the next release.

**Comment by praneshr** [comment]
I feel it's okay to turn off the `strictNullChecks`
