### ISSUE TITLE
You may need an appropriate loader for this filetype

### ISSUE THREAD

**Issue by yamini-krishnamurthy** [praneshr/react-diff-viewer#20]
When I import this package in a Rails/React app I see this error

```
Uncaught Error: Module parse failed: Unexpected token (5:42)
You may need an appropriate loader to handle this file type.
| const emotion_1 = require("emotion");
| exports.default = (styleOverride) => {
|     const { variables: overrideVariables, ...styles } = styleOverride;
|     const variables = {
|         ...{
    at Object.<anonymous> (diff.js:1585)
    at __webpack_require__ (bootstrap 1f5c261f2a8d531ceb44:19)
    at Object.<anonymous> (index.js:7)
    at __webpack_require__ (bootstrap 1f5c261f2a8d531ceb44:19)
    at Object.<anonymous> (HighlightSummary.jsx:52)
    at __webpack_require__ (bootstrap 1f5c261f2a8d531ceb44:19)
    at Object.<anonymous> (checkPropTypes.js:59)
    at __webpack_require__ (bootstrap 1f5c261f2a8d531ceb44:19)
    at Object.<anonymous> (evaluate.jsx:4)
    at __webpack_require__ (bootstrap 1f5c261f2a8d531ceb44:19)
```

I'm not sure if there are some things I'm missing (webpack, babel, etc.)

**Comment by flyYoyo** [comment]
I met the same issue @yamini-krishnamurthy

**Comment by yamini-krishnamurthy** [comment]
Hey, I fixed it by updating my .babelrc. I added `@babel/react`, `@babel/preset-env`, `@babel/plugin-transform-spread` and `@babel/plugin-proposal-class-properties`

**Comment by Aceysx** [comment]
> Hey, I fixed it by updating my .babelrc. I added `@babel/react`, `@babel/preset-env`, `@babel/plugin-transform-spread` and `@babel/plugin-proposal-class-properties`

Hey, could you paste your code?  I tried to update my .babelrc. But it still didn't work. Thanks

**Comment by Neeraj-swarnkar** [comment]
Hi,

I am facing the same issue,
could you please tell me how to fix this ? thanks.

**Comment by Neeraj-swarnkar** [comment]
> Thanks

Did you get the answer for the problem, I am also facing the same issue and not able to resolve this ? Thanks

**Comment by Neeraj-swarnkar** [comment]
> I met the same issue @yamini-krishnamurthy

did you get the solution for this ?

**Comment by DarshanCodehunt** [comment]
> > Hey, I fixed it by updating my .babelrc. I added `@babel/react`, `@babel/preset-env`, `@babel/plugin-transform-spread` and `@babel/plugin-proposal-class-properties`
> 
> Hey, could you paste your code? I tried to update my .babelrc. But it still didn't work. Thanks

Did you find the solution for this?
