### ISSUE TITLE
(Suggestion) Change TSConfig target option to something other than ESNext

### ISSUE THREAD

**Issue by tanelih** [praneshr/react-diff-viewer#21]
Hey,

Would it be possible to `target` something other than `esnext` in the `tsconfig.json` configuration? With the current `esnext` setting, the code will include spread operators, which will cause at least Edge (version 41) to hang.

We've succesfully ran with a `target` setting of `es6` and it seems to work on all "modern" browsers. I can provide a PR if that would help.

**Comment by praneshr** [comment]
Hey @tanelih,

I used `esnext` intentionally. react-diff-viwer is not designed as an UMD module. Meaning, it cannot be consumed directly in browsers without transpiling. So, when you use react-diff-viewer with react in your project, I recommend you to configure webpack, rollup or tsc to compile the final version to any desired target(In your case to `es6`). Hope this helps. Reopen if you need more help. Thanks.
