### ISSUE TITLE
How i can build project in local

### ISSUE THREAD

**Issue by Neeraj-swarnkar** [praneshr/react-diff-viewer#22]
I have cloned the project in my local
did npn i for dependencies
But i am not able to run this locally, could you tell me how to use this ?

I am running as - npm run devServer

**Comment by praneshr** [comment]
Thanks for pointing out. I've updated the README.

Fixed (b8802562bec8c6e8e130cfbab10cd6c37601d8ff)

**Comment by Neeraj-swarnkar** [comment]
Thanks, somehow before you updating the read me I figured it out how to run it. Thanks.
npm build
npm run start:examples

did the trick.
