### ISSUE TITLE
Can I use this library in my enterprise project ?

### ISSUE THREAD

**Issue by Neeraj-swarnkar** [praneshr/react-diff-viewer#23]
Here I am looking for few details -

Can I use this library in my enterprise company project ? I can see this is MIT license so I think I can use it.
Your library or react component use https://github.com/kpdecker/jsdiff jsdiff which seems to be under BSD licensing, https://github.com/kpdecker/jsdiff/blob/master/LICENSE

Can i assume this is stable component we can refer and use in project.

Thanks for awesome library and work, looking forward to hear from you. Thanks.

**Comment by praneshr** [comment]
You need to check with your legal team regarding this. Thanks.
