### ISSUE TITLE
Text diff result is unexpected when the oldvalue="1\n2\n3" and newvalue="1\n2"

### ISSUE THREAD

**Issue by cczz598** [praneshr/react-diff-viewer#29]
**[version: 1.1.0]**

When I use mock value,  oldvalue="`1\n2\n3`" and new value="`1\n2`", this diff viewer shows unexpected result, as follow picture.
![image](https://user-images.githubusercontent.com/5918421/64308010-74b6ef00-cfca-11e9-850f-f0a9a6c24579.png)

The the third line on the left side should be texted "3" with "remove-line" style. In fact, "3" is texted on the right side, and the third line number is 2. 

I'm confused. Is this a bug?

**Comment by praneshr** [comment]
Hi @cczz598, there were few bugs in computing diff with whitespaces. Please use [v2.0](https://github.com/praneshr/react-diff-viewer#install)
