### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by fdemello** [praneshr/react-diff-viewer#30]
Native dark mode support would be nice.

**Comment by praneshr** [comment]
It will be added in the next major version😃

**Comment by fdemello** [comment]
@praneshr In my implementation, I used these colors.

```

**Comment by praneshr** [comment]
Hello! [v3.0.0 beta](https://github.com/praneshr/react-diff-viewer/tree/v3.0.0) is now available. This issue is addressed in this release. Try it out and provide feedback.
