### ISSUE TITLE
Column title in split view

### ISSUE THREAD

**Issue by mikecole** [praneshr/react-diff-viewer#34]
I am showing a diff using split view, and at the top of both columns I'd like to set arbitrary text. I would like to show date values specifying the time the change was made, along with some other metadata. Is this currently possible? Thanks!

**Comment by praneshr** [comment]
Thanks for the suggestion. Sounds like a valid feature request. I will try to add it in the upcoming version. Meanwhile, you can add titles outside of the diff viewer.

**Comment by praneshr** [comment]
Hello! [v3.0.0 beta](https://github.com/praneshr/react-diff-viewer/tree/v3.0.0) is now available. This issue is addressed in this release. Try it out and provide feedback.

**Comment by circAssimilate** [comment]
It (and the compareMethod prop) are working well for me in the beta @praneshr! Thank you!
