### ISSUE TITLE
bug: react element key hardcoded to 100 (?!?), index keys used frequently

### ISSUE THREAD

**Issue by dimitropoulos** [praneshr/react-diff-viewer#35]
Observe the following snippet of code from [index.tsx](https://github.com/praneshr/react-diff-viewer/blob/master/src/index.tsx#L406):

```tsx
<tr key={Math.round(100).toString()}>
```

Now consider the following sandbox example: https://codesandbox.io/embed/proud-firefly-wlko9

This is a serious bug.

This example demonstrates that when there's a row that has a key that's based off of the index two react elements will exist with the same key, which, of course, causes react to go crazy.  In my specific app, which datafetches the thing that's being diffed, it results in the row being duplicated every few seconds (such that if you have the app open for 60 seconds, you might have 60 duplicated rows).

[React depends on keys being unique among siblings.](https://reactjs.org/docs/lists-and-keys.html#keys-must-only-be-unique-among-siblings)

Furthermore, it's widely considered an antipattern to use array indexes as keys [sources: [1](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md), [2](https://medium.com/@vraa/why-using-an-index-as-key-in-react-is-probably-a-bad-idea-7543de68b17c), [3](https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318), [4](https://reactjs.org/docs/lists-and-keys.html#keys)], something that's done very frequently in this project [source [1](https://github.com/praneshr/react-diff-viewer/blob/master/src/index.tsx#L285), [2](https://github.com/praneshr/react-diff-viewer/blob/master/src/index.tsx#L317), [3](https://github.com/praneshr/react-diff-viewer/blob/master/src/index.tsx#L368), [4](https://github.com/praneshr/react-diff-viewer/blob/master/src/index.tsx#L406), [5](https://github.com/praneshr/react-diff-viewer/blob/master/src/index.tsx#L469), [6](https://github.com/praneshr/react-diff-viewer/blob/master/src/index.tsx#L163)].

I understand that this is a tough cookie to crack because with a library like this you don't have very many guarantees.  You can't exactly force the end user to provide an id for every row/column/whatever.  To solve this problem in the past for similar problems I've used some of the solutions suggested in the linked resources on this antipattern above (e.g. [shortid](https://www.npmjs.com/package/shortid)).

This bug was introduced [here](https://github.com/praneshr/react-diff-viewer/commit/c8ef5d38de9ab763792fa7950396543a2f1dd57f#diff-38682f47b0cf12c516bc3714fc45d0fdR229).

**Comment by dimitropoulos** [comment]
As an aside @praneshr I am curious why you wrote `Math.round(100).toString()`, which, so far as I can tell, is logically equivalent to `"100"`.

**Comment by dimitropoulos** [comment]
Also.. for balance: Thank you for open sourcing this project.  From the search I did for all the competition's offerings I found this to be the best.

**Comment by praneshr** [comment]
Hi @dimitropoulos, thanks for pointing this out. This is a serious bug. I meant to write `Math.random().toString()`. I'll release a patch by end of this week.

**Comment by praneshr** [comment]
Fixed in [v2.0.3](https://github.com/praneshr/react-diff-viewer/releases/tag/v2.0.3)

**Comment by dimitropoulos** [comment]
![Screenshot_20191028_122721](https://user-images.githubusercontent.com/15232461/67697065-55ab5c80-f97e-11e9-9e89-7aca45e3fedf.png)

I think @praneshr something happened with the npm release: `lib/index.js` doesn't contain the fix in `v2.0.3`
