### ISSUE TITLE
latest release doesn't seem to include correct code

### ISSUE THREAD

**Issue by dimitropoulos** [praneshr/react-diff-viewer#42]
see: https://github.com/praneshr/react-diff-viewer/issues/35#issuecomment-547029615

**Comment by praneshr** [comment]
Hi @dimitropoulos, thanks for pointing this out. The last version has been pushed without being built. That's the reason for stale file. I've published updated version. Just do `yarn upgrade react-diff-viewer`. Let me know if you face any more problem.

**Comment by dimitropoulos** [comment]
confirmed. thanks!
