### ISSUE TITLE
Issue with showDiffOnly option

### ISSUE THREAD

**Issue by IgorNovokhatny** [praneshr/react-diff-viewer#43]
Hello, 

We would like to report an issue with “showDiffOnly” option. 

The aforementioned option does not always work correctly and despite it is enabled, some lines that have no differences are still displayed. The corresponding lines are not highlighted, however, they shouldn’t be visible at all.  Unfortunately, it was not possible to customize the library in order to resolve the case.

You may find more information on the attached screenshots. Also, the code that reproduces the issue may be found below. 

We would highly appreciate if you provide us with more information regarding issue and fix it if possible.

Hope for your cooperation and look forward to hearing from you soon.

**- Details:**

"react-diff-viewer": "^2.0.1"

**- oldValue:**

```
<div class="test-class">
    <div class="test1-class">
	  <div class="test3-class">
    		<img src="test/src" alt="test alt" height="70px" style="padding: 10px 0 0 0;">
   	</div>  	
  	<p style="padding: 20px 0 10px 0; font-size: 14px; text-align: center; color: #000000; font-weight: 100"><b>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed.</b></p>
    <ul>
      <li style="text-align: left;font-weight: 100;font-size: 14px;padding: 0 0 5px 0;">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt</li>
      <li style="text-align: left;font-weight: 100;font-size: 14px;padding: 0 0 5px 0;">Lorem ipsum dolor sit amet,</li>
    </ul>
    #if(test)
	  <div style="position: absolute; top: 80%; left: 22.5%">
		<button class="testing-class" data-toggle="modal" data-target="#tesing-target">lorem ipsum dolor</button>
	</div>      
</div>
```
 **- newValue:**

```
<div class="test-class">
  <div class="test1-class">
    <div class="test3-class"><img src="test/src" alt="test alt" height="70px" style="padding: 10px 0 0 0;"></div>  	
    <p style="padding: 20px 0 10px 0; font-size: 14px; text-align: center; color: #000000; font-weight: 100"><b>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed.</b></p>
    <ul>
      <li style="text-align: left;font-weight: 100;font-size: 14px;padding: 0 0 5px 0;">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt</li>
      <li style="text-align: left;font-weight: 100;font-size: 14px;padding: 0 0 5px 0;">Lorem ipsum dolor sit amet,</li>
    </ul>
    #if(test)
    <div style="position: absolute; top: 75%; left: 22%">
      <button class="testing-class" data-toggle="modal" data-target="#tesing-target">lorem ipsum dolor
    </button>
  </div>      
</div>
```
 **showDiffOnly disabled**
![all-code](https://user-images.githubusercontent.com/46081499/67942435-7bd03700-fbe0-11e9-8bd2-f2dbab559a36.png)

 **showDiffOnly enabled**
![diff-only](https://user-images.githubusercontent.com/46081499/67942436-7bd03700-fbe0-11e9-9763-f4deea786a44.png)

**Comment by praneshr** [comment]
Hi @IgorNovokhatny, the extra lines are there for a reason. `showDiffOnly` option will still show some line when the number of lines between two diffs are less. It is there for better UX. You can control the number of lines to be shown using `extraLinesSurroundingDiff`. 

And I'll also request you to update the package to the latest version.

**Comment by IgorNovokhatny** [comment]
Hello, Pranesh.

Thank you for your response, it is highly appreciated. However, as mentioned in the previous message, it is not possible to customize the library with the provided settings including `extraLinesSurroundingDiff`. 

I attempted to set the aforementioned option to 0, 1 and some other values, still, it did not resolve the issue with several extra lines. Moreover, they are display rather randomly. 

Also, updating the package to the latest version (2.0.5) did not help. 

Is there anything else you may suggest?  I would highly appreciate of you look into the issue deeper and fix it if possible. 

Have a great day ahead!
