### ISSUE TITLE
Add a class to customize the width of the table cell

### ISSUE THREAD

**Issue by praneshr** [praneshr/react-diff-viewer#48]

**Comment by circAssimilate** [comment]
@praneshr, +1 on this. We would also very much love the option to ensure the before and/ after was 50 / 50.

**Comment by praneshr** [comment]
Hello! [v3.0.0 beta](https://github.com/praneshr/react-diff-viewer/tree/v3.0.0) is now available. This issue is addressed in this release. Try it out and provide feedback.
