### ISSUE TITLE
Support Disable Code Fold Message

### ISSUE THREAD

**Issue by todd** [praneshr/react-diff-viewer#49]
Hi there,

I have a use-case where I need to hide the code fold message. Passing `undefined` to `codeFoldRenderer` simply falls back to the default behavior. It's possible to pass an override function, but this feels like a bit of a hack. Would a PR be accepted to support a `displayCodeFoldMessage` property that would optionally allow users to disable the code fold message? The default value would be `true` to support backwards-compatibility.

Thanks for all the work on this component!

**Comment by todd** [comment]
Additionally/alternatively, would a style override for the code fold be welcomed as well?

**Comment by praneshr** [comment]
Hey @todd, did you try using `codeFoldMessageRenderer` and return an empty string?. I don't think `displayCodeFoldMessage` will be needed as there is a way to customize the same. If you don't want code folding, set `showDiffOnly` to `false`. Let me know your thoughts.

**Comment by todd** [comment]
I actually managed to do what I needed by using those properties - didn't seem to take immediately in my application, but it eventually sorted itself out. Sorry for the noise.
