### ISSUE TITLE
Typing issue (possibly to do with strict null types)

### ISSUE THREAD

**Issue by jamiewinder** [praneshr/react-diff-viewer#52]
When I build my TypeScript project which uses this library, I get several typing errors in the styles.d.ts file. This appears to be due to the properties of `ReactDiffViewerStyles` being optional properties, but the type of `[key: string]` being `string`, not `string | undefined`.

**Comment by praneshr** [comment]
Hi @jamiewinder, can you share your tsconfig?

**Comment by dodev** [comment]
I'm experiencing the same problem. I have the `strictNullChecks` flag set to `true`.

I see there was an issue regarding this problem - #17 and @praneshr recommended turning off the strict null checks. But there are cases where doing so is very time consuming, i.e. when big chunks of your code depend on that compiler flag.

@praneshr would you please consider @jamiewinder solution to the problem? Then your component will compile fine on projects where `strictNullChecks` is set to `true` or `false`.

**Comment by praneshr** [comment]
Fixed in [v2.0.6](https://github.com/praneshr/react-diff-viewer/releases/tag/v2.0.6)
