### ISSUE TITLE
how to fold json code?

### ISSUE THREAD

**Issue by c1240539157** [praneshr/react-diff-viewer#56]
my json code is too long , it is any possible to fold or expand code manual?
![fold](https://user-images.githubusercontent.com/5763230/70321040-3b0fb180-1861-11ea-8c03-18c64e377d94.jpg)

**Comment by praneshr** [comment]
Can you share the string used?

**Comment by c1240539157** [comment]
{"originalContent":{"compConfig":{"newQualityCommitment":{"depends":null,"label":"质量承诺协议","type":"enumValue","compName":"newQualityCommitment","required":true,"tags":null,"supportSceneUse":true,"readonly":null,"complexComp":false,"dataSource":[{"disabled":false,"text":"同意签署","value":1,"info":null},{"disabled":false,"text":"不同意签署","value":0,"info":null}],"supportUpdate":false,"info":{"help":[],"top":[],"bottom":["签署后，在商品详情页中展示质量承诺标识及品牌承诺信息，不符承诺退一赔一 <a href='//maowo.tmall.com/discussion.htm?spm=a220z.1000885.0.0.gP9SPz&id=79648&circleId=19' target='_blank'>查看协议详情</a>"],"richTip":{"images":[]},"right":[]},"group":null},"newPaimai":{"supportSceneUse":true,"readonly":null,"depends":null,"complexComp":false,"label":"拍卖","type":"basic","compName":"newPaimai","required":true,"supportUpdate":false,"info":{"help":[],"top":[],"bottom":[],"richTip":{"images":[]},"right":[],"preset":false},"tags":null,"group":null},"bidding":{"supportSceneUse":true,"readonly":null,"depends":null,"complexComp":false,"label":"拍卖共建","type":"basic","compName":"bidding","required":true,"supportUpdate":true,"info":{"help":[],"top":[],"bottom":[],"richTip":{"images":[]},"right":[],"preset":false},"tags":null,"group":"product"},"xinpin":{"depends":null,"label":"是否新品","type":"enumValue","compName":"xinpin","required":true,"tags":null,"supportSceneUse":true,"readonly":null,"complexComp":false,"dataSource":[{"disabled":false,"text":"是","value":1,"info":null},{"disabled":false,"text":"否","value":0,"info":null}],"supportUpdate":false,"info":{"help":[],"top":[],"bottom":[],"richTip":{"images":[]},"right":["<a target='_blank' class='wanxiang-knowledge' data-knowledge='13128397' href='//rule.tmall.com/tdetail-629.htm'>[新品打标逻辑]</a><a target='_blank' class='wanxiang-knowledge' data-knowledge='13129610' href='https://maowo.tmall.com/discussion.htm?id=45452&circleId=45'>&nbsp;&nbsp;&nbsp;&nbsp;[新品打标结果查询]</a>"]},"group":null},"recommendReason":{"depends":null,"showCounter":false,"label":"推荐理由","type":"input","compName":"recommendReason","required":null,"tags":["sellerTag_73089"],"supportSceneUse":true,"readonly":null,"complexComp":false,"placeholder":null,"maxLength":30,"supportUpdate":false,"info":{"help":[],"top":[],"bottom":["推荐理由最多15汉字；不允许填写营销词、违禁词等! ","确认以上推荐理由内容为商品真实有效信息，且已阅读<a href='//maowo.tmall.com/discussion.htm?id=90357&circleId=45' target='_blank'>填写规范及处罚规则</a> <a href='//healthcenter.taobao.com/keyword_check.htm' target='_blank'>排查工具</a>"],"richTip":{"images":[]},"right":[]},"group":null},"qualityCommitment":{"supportSceneUse":true,"readonly":null,"depends":null,"complexComp":false,"label":"质量承诺协议","type":"basic","compName":"qualityCommitment","required":true,"supportUpdate":true,"info":{"help":[],"top":[],"bottom":["签署后，在商品详情页中展示质量承诺标识及品牌承诺信息，不符承诺退一赔一 <a href='//maowo.tmall.com/discussion.htm?spm=a220z.1000885.0.0.gP9SPz&id=79648&circleId=19' target='_blank'>查看协议详情</a>"],"richTip":{"images":[]},"right":[]},"tags":null,"group":"post-sale-service"},"shelfTime":{"depends":null,"label":"上架时间","type":"enumValue","compName":"shelfTime","required":true,"tags":null,"supportSceneUse":true,"readonly":null,"complexComp":false,"dataSource":[{"disabled":false,"text":"立刻上架","value":0,"info":{"help":["商品上所有SKU均立刻可售卖"],"top":[],"bottom":[],"richTip":{"images":[]},"right":[],"preset":false}},{"disabled":false,"text":"定时上架","value":1,"info":{"help":["您可以设定商品的正式开始销售时间。","商品定时上架后会向消费者展现，若存在问题，平台将按规则进行管控。"],"top":[],"bottom":[],"richTip":{"images":[]},"right":[],"preset":false}},{"disabled":false,"text":"放入仓库","value":2,"info":{"help":["商品上所有SKU均下架，不可售卖"],"top":[],"bottom":[],"richTip":{"images":[]},"right":[],"preset":false}}],"supportUpdate":true,"info":{"help":[],"top":[],"bottom":[],"richTip":{"images":[]},"right":[],"preset":false},"group":"post-sale-service"},"tmExtractWay":{"supportSceneUse":true,"readonly":null,"depends":null,"complexComp":true,"label":"提取方式","type":"basic","compName":"tmExtractWay","required":true,"supportUpdate":true,"info":{"help":[],"top":[],"bottom":[],"richTip":{"images":[]},"right":[]},"tags":null,"group":"deliver"},"catPath":{"supportSceneUse":true,"readonly":null,"depends":null,"complexComp":false,"label":"类目","type":"basic","compName":"catPath","required":null,"supportUpdate":true,"info":{"help":[],"top":[],"bottom":[],"richTip":{"images":[]},"right":[]},"tags":null,"group":"category"}},"compRules":{"newQualityCommitment":[{"condition":null,"before":null,"value":null,"key":"qualityCommitment-tmall-spuFeatureDisable","desc":null}],"newPaimai":[{"condition":"!isBiddingItem || sourceFromTop","before":null,"value":null,"key":"standard-disable","desc":"拍卖共建组件是否运行  迁移来源: bidding-tmall-disable BiddingCompGpsExtPoint"},{"condition":null,"before":null,"value":null,"key":"bidding-tmall-prepareForSubmit","desc":null}],"bidding":[{"condition":"","before":null,"value":null,"key":"standard-disable","desc":"拍卖共建组件是否运行  迁移来源: bidding-tmall-disable BiddingCompGpsExtPoint"},{"condition":null,"before":null,"value":"","key":"bidding-tmall-prepareForSubmit","desc":null}],"xinpin":[{"condition":null,"before":null,"value":null,"key":"xinpin-tmall-disable","desc":null},{"condition":null,"before":null,"value":null,"key":"xinpin-tmall-prepareForRender-setPeriodExpiredInfo","desc":null},{"condition":null,"before":null,"value":null,"key":"xinpin-tmall-prepareForRender-setSneakerInfo","desc":null},{"condition":null,"before":null,"value":null,"key":"xinpin-tmall-prepareForRender-setSneakerTipsInfo","desc":null},{"condition":null,"before":null,"value":null,"key":"xinpin-tmall-prepareForRender-setQueryTipsInfo","desc":null},{"condition":null,"before":null,"value":null,"key":"xinpin-tmall-prepareForSubmit-setArticleNoImageUrl","desc":null},{"condition":null,"before":null,"value":null,"key":"xinpin-tmall-prepareForSubmit-resetValueWhenEdit","desc":null},{"condition":null,"before":null,"value":null,"key":"xinpinPeriodCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"xinpinArticleImageCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"xinpinCategoryCheck","desc":null}],"recommendReason":[{"condition":null,"before":null,"value":"TMALL_DESCRIPTION","key":"kfcBase","desc":null},{"condition":null,"before":null,"value":null,"key":"recommendReason-tmall-prepareForRender","desc":null},{"condition":null,"before":null,"value":null,"key":"recommendReason-tmall-algorithmicGuide","desc":null}],"qualityCommitment":[{"condition":null,"before":null,"value":null,"key":"qualityCommitment-tmall-spuFeatureDisable","desc":null},{"condition":null,"before":null,"value":null,"key":"standard-disable","desc":null}],"shelfTime":[{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-isEnabled","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-stuff-status-check","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-baseColorNum-check","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-showSkuUpOffShelfTip","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-setUpDownSelfReadonlyForSubAccount","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-buildStartType","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-setLianbaoItemStatus","desc":null},{"condition":"isPublish && !isVipItemFlow && !hasNewService","before":null,"value":null,"key":"shelfTime-tmall-setHomeDecorationItemStatus","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-setNewSereviceItemStatus","desc":null},{"condition":"isPublish && !isVipItemFlow && !hasNewService","before":null,"value":null,"key":"shelfTime-tmall-setCarInstallationItemStatus","desc":null},{"condition":"!isVipItemFlow","before":null,"value":null,"key":"shelfTime-tmall-set3wHaierDpcItemStatus","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-setBrandCardItemStatus","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-autoCc-inStock","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-setStatusForLightItem","desc":null},{"condition":null,"before":null,"value":null,"key":"itemEditMmpCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"lianbaoUpshelfItemCheck","desc":null},{"condition":"isPublish && !isVipItemFlow && !hasNewService","before":null,"value":null,"key":"homeDecorationUpshelfItemCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"newServiceUpshelfItemCheck","desc":null},{"condition":"isPublish && !isVipItemFlow && !hasNewService","before":null,"value":null,"key":"carInstallationUpshelfItemCheck","desc":null},{"condition":"!isVipItemFlow","before":null,"value":null,"key":"3wHaierDpcUpshelfItemCheck","desc":null},{"condition":"isDarwin && !isCombineFlow","before":null,"value":null,"key":"darwinUpshelfItemCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"hscodeUpshelfItemCheck","desc":null},{"condition":"isFastEdit","before":null,"value":null,"key":"codePoolUpshelfItemCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"brandCardMustBeInStockCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"brandCardCanNotUpShelfCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"couponValidOfItemStatusCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"itemTimeOnSaleTimeCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-CunTaoDirect-check","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-prepareForRender-setDateRange","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-fuzzy-renderDefaultStatus","desc":null}],"tmExtractWay":[{"condition":null,"before":null,"value":null,"key":"deliverWay-tmall-disable","desc":null},{"condition":null,"before":null,"value":null,"key":"deliverWayRequired","desc":null},{"condition":null,"before":null,"value":null,"key":"abroadBuyNoLogisticsCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"etcAutoFillNoLogisticsCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"deliverWay-tmall-prepareData","desc":null},{"condition":null,"before":null,"value":null,"key":"deliverWay-tmall-abroadBuyTip","desc":null},{"condition":null,"before":null,"value":null,"key":"deliverWay-tmall-autoCc","desc":null}],"catPath":[{"condition":null,"before":null,"value":null,"key":"productEcardCategoryGrantCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"productCatStatusCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"catpath-tmall-prepareDataForRender","desc":null},{"condition":null,"before":null,"value":null,"key":"catPath-tmall-canChangeCategory","desc":null},{"condition":null,"before":null,"value":null,"key":"catPath-tmall-setupMarkErrorTips","desc":null},{"condition":null,"before":null,"value":null,"key":"catPath-tmall-fastEditHideButton","desc":null},{"condition":null,"before":null,"value":null,"key":"catPath-tmall-draftCanChangeCategory","desc":null}]},"sceneExts":{"abilityTags":[{"tagCode":"sellerTag_73089","tagName":"推荐理由白名单标"}]}},"changedContent":{"compConfig":{"showTitle":{"depends":null,"showCounter":null,"label":"商品展示标题","type":"input","compName":"showTitle","required":false,"tags":null,"supportSceneUse":true,"readonly":null,"complexComp":false,"placeholder":null,"maxLength":60,"supportUpdate":true,"info":{"help":[],"top":[],"bottom":["品牌名+商品名","请您用最简明扼要的文案填写标题名称。表达结构为：品牌名＋材质/功效/风格/规格(主要属性词)＋品名。该名称不影响搜索检索，区别于上方用于搜索的“商品标题”，将被应用到天猫App商品详情页、搜索结果页、购物车等前台页面作为商品展示标题。<a href='//maowo.tmall.com/discussion.htm?id=85595' target='_blank'>查看规范</a>"],"richTip":{"images":[]},"right":[],"preset":false},"group":"desc"},"shelfTime":{"depends":null,"label":"上架时间","type":"enumValue","compName":"shelfTime","required":true,"tags":null,"supportSceneUse":true,"readonly":null,"complexComp":false,"dataSource":[{"disabled":false,"text":"立刻上架","value":0,"info":{"help":["商品上所有SKU均立刻可售卖"],"top":[],"bottom":[],"richTip":{"images":[]},"right":[],"preset":false}},{"disabled":false,"text":"定时上架","value":1,"info":{"help":["您可以设定商品的正式开始销售时间","商品定时上架后会向消费者展现，若存在问题，平台将按规则进行管控。"],"top":[],"bottom":[],"richTip":{"images":[]},"right":[],"preset":false}},{"disabled":false,"text":"放入仓库","value":2,"info":{"help":["商品上所有SKU均下架，不可售卖"],"top":[],"bottom":[],"richTip":{"images":[]},"right":[],"preset":false}}],"supportUpdate":true,"info":{"help":[],"top":[],"bottom":[],"richTip":{"images":[]},"right":[],"preset":false},"group":"post-sale-service"}},"compRules":{"showTitle":[{"condition":null,"before":null,"value":null,"key":"showTitle-tmall-qualityUserDisable","desc":null},{"condition":null,"before":null,"value":null,"key":"kfcWithoutBrand","desc":null},{"condition":"!isNonStandard","before":null,"value":null,"key":"ignoreBrandKeywordCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"showTitleOriginalBrandCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"containProductTitle","desc":null},{"condition":null,"before":null,"value":null,"key":"showTitlePromotionKeyWorkCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"futureTitleContainProductCodeCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"showTitle-tmall-prepareRenderMaxLength","desc":null},{"condition":null,"before":null,"value":null,"key":"showTitle-tmall-containSpuTitle","desc":null},{"condition":null,"before":null,"value":null,"key":"showTitle-tmall-prepareSubmitMaxLength","desc":null},{"condition":null,"before":null,"value":null,"key":"titleBookSpuCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"title-tmall-cocoaButterReplacer-setMaxLengthForRender","desc":null},{"condition":null,"before":null,"value":null,"key":"title-tmall-cocoaButterReplacer-setMaxLengthForSubmit","desc":null},{"condition":null,"before":null,"value":null,"key":"title-tmall-cocoaButterReplacer-trimTailBeforeRender","desc":null},{"condition":null,"before":null,"value":null,"key":"title-tmall-cocoaButterReplacer-appendTailBeforeSubmit","desc":null},{"condition":null,"before":null,"value":null,"key":"showTitle-tmall-setAsProductTitle-beforeRender","desc":null},{"condition":null,"before":null,"value":null,"key":"showTitle-tmall-setAsProductTitle-beforeSubmit","desc":null},{"condition":null,"before":null,"value":null,"key":"showTitleXinpinKeywordCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"showTitle-tmallHealth-setAsProductTitle-before","desc":null},{"condition":null,"before":null,"value":null,"key":"showTitleLengthCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"showTitleDarwinNewStyleProductCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"showTitle-tmall-tipForRender","desc":null},{"condition":null,"before":null,"value":null,"key":"showTitle-tmall-containsBrandName","desc":null}],"shelfTime":[{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-isEnabled","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-stuff-status-check","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-baseColorNum-check","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-showSkuUpOffShelfTip","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-setUpDownSelfReadonlyForSubAccount","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-buildStartType","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-setLianbaoItemStatus","desc":null},{"condition":"isPublish && !isVipItemFlow && !hasNewService","before":null,"value":null,"key":"shelfTime-tmall-setHomeDecorationItemStatus","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-setNewSereviceItemStatus","desc":null},{"condition":"isPublish && !isVipItemFlow && !hasNewService","before":null,"value":null,"key":"shelfTime-tmall-setCarInstallationItemStatus","desc":null},{"condition":"!isVipItemFlow","before":null,"value":null,"key":"shelfTime-tmall-set3wHaierDpcItemStatus","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-setBrandCardItemStatus","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-autoCc-inStock","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-setStatusForLightItem","desc":null},{"condition":null,"before":null,"value":null,"key":"itemEditMmpCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"lianbaoUpshelfItemCheck","desc":null},{"condition":"isPublish && !isVipItemFlow && !hasNewService","before":null,"value":null,"key":"homeDecorationUpshelfItemCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"newServiceUpshelfItemCheck","desc":null},{"condition":"isPublish && !isVipItemFlow && !hasNewService","before":null,"value":null,"key":"carInstallationUpshelfItemCheck","desc":null},{"condition":"!isVipItemFlow","before":null,"value":null,"key":"3wHaierDpcUpshelfItemCheck","desc":null},{"condition":"isDarwin && !isCombineFlow","before":null,"value":null,"key":"darwinUpshelfItemCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"hscodeUpshelfItemCheck","desc":null},{"condition":"isFastEdit","before":null,"value":null,"key":"codePoolUpshelfItemCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"brandCardMustBeInStockCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"brandCardCanNotUpShelfCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"couponValidOfItemStatusCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"itemTimeOnSaleTimeCheck","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-CunTaoDirect-check","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-prepareForRender-setDateRange","desc":null},{"condition":null,"before":null,"value":null,"key":"shelfTime-tmall-fuzzy-renderDefaultStatus","desc":null}]}}}

**Comment by praneshr** [comment]
Since, the text in the left is a diff(removed), it cannot be folded. Folding it will be a bad user experience. 

This is working as expected.
