### ISSUE TITLE
package in npm lack of build files.

### ISSUE THREAD

**Issue by liudonghua123** [praneshr/react-diff-viewer#6]
I installed this package via `npm i -S react-diff-viewer`, And I used `ReactDiffViewer` in my code, but my app complained that `react-diff-viewer` not found like this.
```
Module not found: Can't resolve 'react-diff-viewer' in 'D:\code\electron\react-material-electron\src\pages'
Compiling...
Failed to compile.
```

I checked the `node_modules/react-diff-viewer` and found that no `lib` directory exits there.

So I think you should `npm run build` before publish to npm. Currently, I manual build this package and copy `lib` directory to `node_modules/react-diff-viewer`.

**Comment by praneshr** [comment]
Fixed in https://github.com/praneshr/react-diff-viewer/commit/a07b292fb10e70d1021f6de11d94db09ad6789ad
