### ISSUE TITLE
Unified (non-split) view without line numbers seems to add extra <td>

### ISSUE THREAD

**Issue by circAssimilate** [praneshr/react-diff-viewer#60]
Here's a screenshot from my local Storybook:
![image](https://user-images.githubusercontent.com/7128855/71523959-f213b180-2890-11ea-8d7e-c88f03f1b293.png)

Steps to reproduce:
- `hideLineNumbers{true}`
- `showDiffOnly{true}`
- `splitView{false}`
- Then `oldValue` and `newValue` should have code that is changed on at least one line but is the same on more than 3 lines surrounding.

The result is the screenshot above. I notice that removing the `td` from the Elements panel seems to resolve it. So this element:

![image](https://user-images.githubusercontent.com/7128855/71524081-867e1400-2891-11ea-9674-d1c692acc636.png)

When removed makes it look like this:

![image](https://user-images.githubusercontent.com/7128855/71524124-ac0b1d80-2891-11ea-878c-2ccdc2a5fbda.png)

I'm thinking https://github.com/praneshr/react-diff-viewer/blob/fb96ee94eb15ea14902ae99251156f30a66f49a7/src/index.tsx#L433 should actually be:

```
{!splitView ? content : null}
```

So `splitView={true}` will add an extra cell but unified view will not. If you think that's a reasonable approach, I can make a PR!

**Comment by circAssimilate** [comment]
I added #61 to fix this!

**Comment by praneshr** [comment]
Ah! Thanks for pointing this out. I'll review the PR by this weekend.
