### ISSUE TITLE
[feature request] Export Package as ES5

### ISSUE THREAD

**Issue by circAssimilate** [praneshr/react-diff-viewer#62]
This is related to the core issue in https://github.com/praneshr/react-diff-viewer/issues/47, but offers a suggestion on a solution. From @jamesopti on https://github.com/optimizely/oui/pull/1271:

>This (https://github.com/optimizely/oui/pull/1271/files#diff-11e9f7f953edc64ba14b0cc350ae7b9dR42) works as a crutch, but is not ideal.
>
>Could you open a ticket with the package maintainer?
>
>There is a lot of debate in the community about whether the package.json module should be used purely to indicate ESM (the spec) or to indicate ES2015+ code (which has become common practice).
>
>I think the simple solution here is for the package maintainer to just export an ES5 package. It's pretty straightforward.
>
>More on this topic here: https://babeljs.io/blog/2018/06/26/on-consuming-and-publishing-es2015+-packages

@praneshr, reading through the related issues it sounds like you may have strong feelings that this should be handled by the consumer. Curious though, do you think there are any drawbacks in exporting as es5? I think it would make this module more easily consumable for many more projects without custom configuration like we ended up doing (hopefully only temporarily).

If it's less of a philosophical difference and more of a question of the actual human work it would add, I'd be happy to take a stab at it.

**Comment by praneshr** [comment]
Hi @circAssimilate, thanks for the point and sorry for the delayed response. Since exporting the library as `esnext` is causing a lot of trouble than benefits, I am considering exporting the library as `es5`. I'll release a patch by the end of next week.

**Comment by circAssimilate** [comment]
Thank you, @praneshr! Let me know if I can support in any way!

**Comment by brianorwhatever** [comment]
would love to see an es5 export land in this package soon as it's causing me a lot of headache as well

**Comment by praneshr** [comment]
Fixed in [v3.1.0](https://github.com/praneshr/react-diff-viewer/releases/tag/v3.1.0)
