### ISSUE TITLE
Uncaught Error: Cannot find module "./styles"

### ISSUE THREAD

**Issue by OhCoder** [praneshr/react-diff-viewer#66]
<img width="930" alt="C3D742DF-E1E7-43FE-9A5F-3552BA847A6D" src="https://user-images.githubusercontent.com/890676/74723532-b6d0a600-5275-11ea-94f1-2f11f8a8c115.png">

hi, everyone!
I installed 3.0.1 version, the error need me to config webpack, I'm not sure what should I do......

Thanks!!

**Comment by OhCoder** [comment]
maybe is my webpack version too old, not sure......

**Comment by praneshr** [comment]
Are you using TS or JS?

**Comment by vbatr** [comment]
Hi @OhCoder, I had the same issue.
In my case fix was - migrate from react-scripts-ts to react-scripts.

**Comment by OhCoder** [comment]
@praneshr I use js.

@vbatr Thanks for your help. My project is too old, I tried my newer project, don't meet the issue, my newer project is using js too.

**Comment by praneshr** [comment]
You need to right babel preset to support spread operator.
