### ISSUE TITLE
Title colspan bug when setting `splitView` and `hideLineNumbers`

### ISSUE THREAD

**Issue by olee** [praneshr/react-diff-viewer#68]
When `splitView` and `hideLineNumbers` are set to true, the colspan [here](https://github.com/praneshr/react-diff-viewer/blob/master/src/index.tsx#L532) should be 2 instead of 3

**Comment by praneshr** [comment]
Fixed in [v3.1.0](https://github.com/praneshr/react-diff-viewer/releases/tag/v3.1.0)

**Comment by flyYoyo** [comment]
not fixed, the colspan is still 3

**Comment by flyYoyo** [comment]
> Fixed in [v3.1.0](https://github.com/praneshr/react-diff-viewer/releases/tag/v3.1.0)

not fixed, the colspan is still 3

**Comment by flyYoyo** [comment]
@praneshr not fixed, the colspan is still 3
