### ISSUE TITLE
Remove engines requirement

### ISSUE THREAD

**Issue by olee** [praneshr/react-diff-viewer#69]
Please remove the engines requirement from package.json as there is no reason to include such an annoying field.
Or at lease make it something like `{ "node": ">= 8" }`

**Comment by Anoian** [comment]
Yes please do this.

We use the newest node version 13 and now have to always run `yarn install --ignore-engines` and that really should not be the case.

**Comment by olee** [comment]
@praneshr think you could merge and publish this?

**Comment by praneshr** [comment]
Fixed in [v3.0.2](https://github.com/praneshr/react-diff-viewer/releases/tag/v3.0.2)
