### ISSUE TITLE
Could not find a declaration file for module...implicitly has an 'any' type

### ISSUE THREAD

**Issue by amandarice** [praneshr/react-diff-viewer#7]
When I try to import ReactDiffViewer, typescript throws this nasty error: "Could not find a declaration file for module...implicitly has an 'any' type." Turns out, the solution is simple, which you can find here: https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam. 

Tl;dr: could you please modify your package.json to have these two lines?

"main": "lib/index",
"typings": "lib/index",

^ removes the .js at the end of "lib/index.js" and adds typings

This solved the problem locally for me, but it'd be nice if this fix was automatically included for everyone!

**Comment by praneshr** [comment]
Fixed in https://github.com/praneshr/react-diff-viewer/pull/8
