### ISSUE TITLE
Help - Single line text diff?

### ISSUE THREAD

**Issue by BaileyMillerSSI** [praneshr/react-diff-viewer#73]
I really like this library over the alternatives but I cannot seem to find a configuration that does a single line diff? I have to work within the setup UI designs for a project but don't believe this library can do what I am looking for. 

Using another library I can do this, but I would prefer to use `react-diff-viewer`.
![image](https://user-images.githubusercontent.com/14271740/77916935-dd680080-7267-11ea-97e1-7d3dc7777157.png)

**Comment by praneshr** [comment]
@BaileyMillerSSI - Unfortunately, this is not supported at the moment. But, if you prefer you can try the `inline` mode offered by `react-diff-viewer` by setting `splitView={false}`.

**Comment by BaileyMillerSSI** [comment]
Thanks for the quick reply, I actually found the same diffing library this project uses and wrote my own single line diffing component.

**Comment by philly-vanilly** [comment]
Please reopen this issue, I need this feature too. ATM I will do the same as OP and use diff directly without a wrapper package, but it would be nice if this feature came out of the box

**Comment by BaileyMillerSSI** [comment]
@philly-vanilly I ended up writing my own component with the some diffing library and it works really well. I would recommend you do the some. l can share my code if you need.

**Comment by desmondandersen** [comment]
@BaileyMillerSSI Hi would you be still willing to share your code if you still have it? I am trying to do something similar. Thanks!

**Comment by BaileyMillerSSI** [comment]
@desmondandersen 
https://stackblitz.com/edit/react-ts-fp73qu?file=App.tsx
