### ISSUE TITLE
XML aligning to right hand column

### ISSUE THREAD

**Issue by phil-andrews** [praneshr/react-diff-viewer#76]
I might just be doing something wrong. But when I input an XML string it right aligns to the code view window as seen in the screen shot. It right aligns for unified/split views. Is there something particular I need to do for xml?

```
    <ReactDiffViewer
      oldValue={oldCode}
      newValue={props.codeString}
      splitView={true}
    />
```

![Screen Shot 2020-04-03 at 5 53 45 PM](https://user-images.githubusercontent.com/14335126/78408209-813d0d80-75d4-11ea-8bfa-6f893c4e64d0.png)

**Comment by praneshr** [comment]
@phil-andrews Can you check if any styles are being applied to the table row?

**Comment by phil-andrews** [comment]
Yes, styles are being added. `css-1n7ec1i-line` which is inheriting `text-right` where alignment is marked as `!important`

![Screen Shot 2020-04-05 at 10 37 23 AM](https://user-images.githubusercontent.com/14335126/78501367-73e56780-7729-11ea-9c01-41b71be9b9d4.png)

**Comment by praneshr** [comment]
@phil-andrews `text-align: right` is not set by `react-diff-viewer`. Can you verify?

**Comment by phil-andrews** [comment]
Ah, my mistake. You're right it's inheriting from the bootstrap parent container. Sorry about that
