### ISSUE TITLE
When splitView is set to false, both line numbers still show up

### ISSUE THREAD

**Issue by RyanWarner** [praneshr/react-diff-viewer#79]
Thank you for the amazing library.

I'm seeing two columns for line numbers in `unified` view, which seems unintended (correct me if I'm wrong!).

See this codesandbox: https://codesandbox.io/s/blissful-jepsen-kx7zi?file=/src/App.js

![Screen Shot 2020-04-22 at 5 05 41 PM](https://user-images.githubusercontent.com/1595979/80033934-8bf40f80-84bb-11ea-9a8b-35e0db923411.png)

**Comment by praneshr** [comment]
Thanks for the question. Yes, it is intentional. Left column page number represents the old file and the right column represents the new file. Just like Github diff.

Ref: https://github.com/praneshr/react-diff-viewer/commit/37e4418874fea6be08576230c300c44ad1df7f03?diff=unified
