### ISSUE TITLE
How to disable codeFoldMessageRenderer

### ISSUE THREAD

**Issue by Rajdeepc** [praneshr/react-diff-viewer#86]
My Use Case:
I don't want the message "Expand 14 lines" . I want to show the user all of the JSON at once.
I know codeFoldMessageRenderer - this prop does it. But not able to achieve the result.

How to disable it?

**Comment by Rajdeepc** [comment]
Duplicate

**Comment by AlisanCakir** [comment]
So do "I don't want the message "Expand 14 lines" . I want to show the user all of the JSON at once." thing how can you do that @Rajdeepc
